name: Deploy the main branch
on:
  push:
    branches:
      - main

jobs:
  linting:
    name: Lints the codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint files
        run: yarn lint --diagnostic-level=error

  typecheck:
    name: Validates the codebase types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Typecheck
        run: yarn typecheck

  deploy:
    name: Deploy to Firebase Development
    runs-on: ubuntu-latest
    needs: [linting, typecheck]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Deploy Development environment
        run: yarn deploy:development --token "${{ secrets.FIREBASE_TOKEN }}" --force
      - name: Deploy Production environment
        run: yarn deploy:production --token "${{ secrets.FIREBASE_TOKEN }}" --force
